name: Descargar OCS
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar imagen
        run: docker pull docker.io/ocsinventory/ocsinventory:latest
      - name: Empaquetar imagen
        run: docker save -o ocs_image.tar docker.io/ocsinventory/ocsinventory:latest
      - name: Subir archivo
        uses: actions/upload-artifact@v4
        with:
          name: imagen-ocs
          path: ocs_image.tar
